#!/usr/bin/env python3
"""
Simple API test script for Docker environment
"""
import requests
import json
import time
import sys
import os

API_BASE_URL = "http://localhost:8001"

def wait_for_api(max_retries=30):
    """Wait for API to be ready"""
    print("🔍 Waiting for API to be ready...")
    
    for i in range(max_retries):
        try:
            response = requests.get(f"{API_BASE_URL}/health", timeout=5)
            if response.status_code == 200:
                print("✅ API is ready!")
                return True
        except requests.exceptions.RequestException:
            pass
        
        print(f"⏳ Waiting... ({i+1}/{max_retries})")
        time.sleep(2)
    
    print("❌ API failed to start")
    return False

def get_test_api_key():
    """Get test API key from database setup"""
    try:
        # Read test data if available
        test_data_file = "/app/test_data.json"
        if os.path.exists(test_data_file):
            with open(test_data_file, 'r') as f:
                test_data = json.load(f)
                return test_data.get('api_key')
    except Exception as e:
        print(f"⚠️  Could not read test data: {e}")
    
    # Default test API key (from sqlite_setup.py)
    return "vp_test_key_12345"  # This will be generated by setup

def test_health_endpoint():
    """Test health endpoint"""
    print("\n🧪 Testing health endpoint...")
    
    try:
        response = requests.get(f"{API_BASE_URL}/health")
        assert response.status_code == 200, f"Expected 200, got {response.status_code}"
        
        data = response.json()
        assert "status" in data, "Response missing 'status' field"
        assert "services" in data, "Response missing 'services' field"
        
        print(f"✅ Health check passed: {data['status']}")
        return True
        
    except Exception as e:
        print(f"❌ Health check failed: {e}")
        return False

def test_root_endpoint():
    """Test root endpoint"""
    print("\n🧪 Testing root endpoint...")
    
    try:
        response = requests.get(f"{API_BASE_URL}/")
        assert response.status_code == 200, f"Expected 200, got {response.status_code}"
        
        data = response.json()
        assert "status" in data, "Response missing 'status' field"
        
        print(f"✅ Root endpoint passed: {data['status']}")
        return True
        
    except Exception as e:
        print(f"❌ Root endpoint failed: {e}")
        return False

def test_credits_endpoint(api_key):
    """Test credits endpoint with authentication"""
    print("\n🧪 Testing credits endpoint...")
    
    try:
        headers = {"Authorization": f"Bearer {api_key}"}
        response = requests.get(f"{API_BASE_URL}/credits", headers=headers)
        
        if response.status_code == 401:
            print("⚠️  Authentication failed - API key might be invalid")
            return False
        
        assert response.status_code == 200, f"Expected 200, got {response.status_code}"
        
        data = response.json()
        assert "total_credits" in data, "Response missing 'total_credits' field"
        assert "remaining_credits" in data, "Response missing 'remaining_credits' field"
        
        print(f"✅ Credits check passed: {data['remaining_credits']} credits available")
        return True
        
    except Exception as e:
        print(f"❌ Credits endpoint failed: {e}")
        return False

def test_credit_estimation(api_key):
    """Test credit estimation endpoint"""
    print("\n🧪 Testing credit estimation...")
    
    try:
        headers = {"Authorization": f"Bearer {api_key}"}
        
        estimation_data = {
            "job_type": "simple_merge",
            "videos": [
                {"url": "https://example.com/video1.mp4", "duration": 30.0, "order_index": 0},
                {"url": "https://example.com/video2.mp4", "duration": 45.0, "order_index": 1}
            ],
            "processing_options": {
                "platform": "youtube",
                "quality_preset": "balanced"
            }
        }
        
        response = requests.post(
            f"{API_BASE_URL}/credits/estimate",
            json=estimation_data,
            headers=headers
        )
        
        assert response.status_code == 200, f"Expected 200, got {response.status_code}"
        
        data = response.json()
        assert "estimated_credits" in data, "Response missing 'estimated_credits' field"
        assert "breakdown" in data, "Response missing 'breakdown' field"
        
        print(f"✅ Credit estimation passed: {data['estimated_credits']} credits estimated")
        print(f"   Breakdown: {data['breakdown']}")
        return True
        
    except Exception as e:
        print(f"❌ Credit estimation failed: {e}")
        return False

def test_job_creation(api_key):
    """Test job creation endpoint"""
    print("\n🧪 Testing job creation...")
    
    try:
        headers = {"Authorization": f"Bearer {api_key}"}
        
        job_data = {
            "job_type": "simple_merge",
            "videos": [
                {"url": "https://example.com/video1.mp4", "order_index": 0},
                {"url": "https://example.com/video2.mp4", "order_index": 1}
            ],
            "processing_options": {
                "platform": "youtube",
                "quality_preset": "fast"
            }
        }
        
        response = requests.post(
            f"{API_BASE_URL}/jobs",
            json=job_data,
            headers=headers
        )
        
        if response.status_code == 402:
            print("⚠️  Insufficient credits for job creation")
            return False
        
        assert response.status_code == 200, f"Expected 200, got {response.status_code}"
        
        data = response.json()
        assert "id" in data, "Response missing 'id' field"
        assert "status" in data, "Response missing 'status' field"
        
        job_id = data["id"]
        print(f"✅ Job creation passed: {job_id}")
        print(f"   Status: {data['status']}")
        print(f"   Estimated credits: {data.get('estimated_credits', 0)}")
        
        # Test job status endpoint
        status_response = requests.get(f"{API_BASE_URL}/jobs/{job_id}", headers=headers)
        assert status_response.status_code == 200, "Job status check failed"
        
        status_data = status_response.json()
        print(f"✅ Job status check passed: {status_data['job']['status']}")
        
        return True
        
    except Exception as e:
        print(f"❌ Job creation failed: {e}")
        return False

def test_jobs_list(api_key):
    """Test jobs listing endpoint"""
    print("\n🧪 Testing jobs listing...")
    
    try:
        headers = {"Authorization": f"Bearer {api_key}"}
        response = requests.get(f"{API_BASE_URL}/jobs", headers=headers)
        
        assert response.status_code == 200, f"Expected 200, got {response.status_code}"
        
        data = response.json()
        assert "jobs" in data, "Response missing 'jobs' field"
        assert "total_count" in data, "Response missing 'total_count' field"
        
        print(f"✅ Jobs listing passed: {data['total_count']} total jobs")
        return True
        
    except Exception as e:
        print(f"❌ Jobs listing failed: {e}")
        return False

def main():
    """Main test function"""
    print("🎯 Video Processing API - Simple Test Suite")
    print("=" * 50)
    
    # Wait for API to be ready
    if not wait_for_api():
        sys.exit(1)
    
    # Get test API key
    api_key = get_test_api_key()
    if not api_key:
        print("❌ No test API key available")
        sys.exit(1)
    
    print(f"🔑 Using API key: {api_key[:20]}...")
    
    # Run tests
    tests = [
        ("Health Endpoint", test_health_endpoint, []),
        ("Root Endpoint", test_root_endpoint, []),
        ("Credits Endpoint", test_credits_endpoint, [api_key]),
        ("Credit Estimation", test_credit_estimation, [api_key]),
        ("Job Creation", test_job_creation, [api_key]),
        ("Jobs Listing", test_jobs_list, [api_key])
    ]
    
    results = {}
    
    for test_name, test_func, args in tests:
        try:
            results[test_name] = test_func(*args)
        except Exception as e:
            print(f"❌ {test_name} crashed: {e}")
            results[test_name] = False
    
    # Summary
    print("\n" + "=" * 50)
    print("📊 Test Summary")
    print("=" * 50)
    
    passed = 0
    total = len(results)
    
    for test_name, result in results.items():
        status = "✅ PASSED" if result else "❌ FAILED"
        print(f"{test_name}: {status}")
        if result:
            passed += 1
    
    print(f"\nResults: {passed}/{total} tests passed")
    
    if passed == total:
        print("🎉 All tests passed!")
        sys.exit(0)
    else:
        print("💥 Some tests failed!")
        sys.exit(1)

if __name__ == "__main__":
    main()
